### ISSUE TITLE
Project Questions and Features

### ISSUE THREAD

**Issue by nicotravassos** [LubosTran/react-tribes-frontend#1]
Hi @LubosTran,

1. Do you have a life version of this project which I can look at?
2. Does this project have a back-end because this is the front-end repository?
3. Could you hook a PostgreSQL database to this project?

**Comment by LubosTran** [comment]
Hello Mr Nico,

I believe you are from Cleevio right?

I am very very sorry for the late reply. I've been very busy today with in
the restaurant I'm working in during my job hunting and I can only touch my
phone just now.
I don't know if your colleague has mentioned my situation but I will
forward the email to clarify my late response, right after this one.

Regarding your questions
- This is where we deploy our project :
https://deploy-preview-164--react-tribes.netlify.com/login
- Yes, we have a backend, in Java, but from other team in our cohort. I
belong to the front-end team with 2 other people.
- I'm not sure, our mentor connect the back end and the front end.

Thank you for your time,
Luboš.

**Comment by nicotravassos** [comment]
Thank you @LubosTran
